### ISSUE TITLE
NullPointerException during Load Testing.

### ISSUE THREAD

**Issue by kevindevries** [emqtt/mqtt-jmeter#16]
Currently using JMeter version 3.2 with mqtt-jmeter v0.93.
Doing load testing with JMeter and getting a NullPointerException as shown in logs below.
If anyone has seen a similar issue or has any suggestions it would be appreciated.
```log
2017-07-05 11:13:16,748 INFO o.a.j.t.JMeterThread: Thread is done: Connect Clients 1-12904
2017-07-05 11:13:16,748 INFO o.a.j.t.JMeterThread: Thread finished: Connect Clients 1-12904
2017-07-05 11:13:16,748 INFO o.a.j.t.JMeterThread: Thread started: Connect Clients 1-12912
2017-07-05 11:13:16,753 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NullPointerException: null
	at org.fusesource.mqtt.client.CallbackConnection$7.run(CallbackConnection.java:450) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$3.run(HeartBeatMonitor.java:87) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.HeartBeatMonitor$1.run(HeartBeatMonitor.java:65) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100) [mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77) [mqtt-xmeter-jar-with-dependencies.jar:?]
2017-07-05 11:13:16,757 ERROR n.x.s.ConnectionSampler: Too many open files
java.net.SocketException: Too many open files
	at sun.nio.ch.Net.socket0(Native Method) ~[?:1.8.0_131]
	at sun.nio.ch.Net.socket(Net.java:411) ~[?:1.8.0_131]
	at sun.nio.ch.Net.socket(Net.java:404) ~[?:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105) ~[?:1.8.0_131]
	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60) ~[?:1.8.0_131]
	at java.nio.channels.SocketChannel.open(SocketChannel.java:145) ~[?:1.8.0_131]
	at org.fusesource.hawtdispatch.transport.TcpTransport.connecting(TcpTransport.java:424) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.mqtt.client.CallbackConnection.createTransport(CallbackConnection.java:286) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.mqtt.client.CallbackConnection.connect(CallbackConnection.java:139) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.mqtt.client.FutureConnection$2.run(FutureConnection.java:146) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
```

**Comment by rende2005** [comment]
Hi Kevin,

Since the exception shows "Too many open files", I wonder what is your test scenario, how many virtual users, connection sampler parameters being used, delay time and so on.
What if you increase the open file limits before launching jmeter, say via "ulimit -n 10240" for Linux?

**Comment by Raul666** [comment]
Hoeveel threads are you using?
wat is your rampuptime ?
wat is your JVM heap?
It seems after few threads have finished you get this error ?

**Comment by rende2005** [comment]
@kevindevries 
Is it still an issue to you?  We may need more information in order to pinpoint the problem.

**Comment by kevindevries** [comment]
Hi,
Sorry ya I managed to pretty much solve the issue. I believe it was more a limitation on my own system due to the amount of threads being sent at once. Using loops and allowing for a lower amount of connections per second seemed to solve my issue. I don't believe there was an error on the part of jmeter or mqtt. 
Thanks for your time.

Regards,
Kevin

**Comment by rende2005** [comment]
Great! Thanks for the confirmation!
