### ISSUE TITLE
关于JMeter MQTT插件是否可以连接Azure？

### ISSUE THREAD

**Issue by lijiwei** [emqtt/mqtt-jmeter#20]
最近有个任务，需要连接Azure ,但是每次都没有成功
报错
`java.io.EOFException: Peer disconnected
	at org.fusesource.hawtdispatch.transport.AbstractProtocolCodec.read(AbstractProtocolCodec.java:331) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:710) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.SslTransport.drainInbound(SslTransport.java:276) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77) ~[mqtt-xmeter-jar-with-dependencies.jar:?]`

有试过连接Azure IOTHub中心的吗？

**Comment by jinfahua** [comment]
Yes, please refer to https://github.com/emqtt/mqtt-jmeter/issues/4 . You need to specify the correct ClientId.

**Comment by jinfahua** [comment]
Close the issue.
