### ISSUE TITLE
TimeoutException when connecting to Azure Iothub

### ISSUE THREAD

**Issue by AzureUser123** [emqtt/mqtt-jmeter#21]
Hi,
I've been trying to send a payload data to a device in azure iot hub through this mqtt plugin in jmeter. But it doesn't connect to the hub and there's an exception throwing as below.

```
ERROR - net.xmeter.samplers.PubSampler:  java.util.concurrent.TimeoutException
	at org.fusesource.mqtt.client.Promise.await(Promise.java:83)
	at net.xmeter.samplers.PubSampler.sample(PubSampler.java:141)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jinfahua** [comment]
Please refer to https://github.com/emqtt/mqtt-jmeter/issues/4. You probably need to specify a correct clientId.

**Comment by AzureUser123** [comment]
I have used deviceId as the clientId as mentioned. But still it doesn't connect.

**Comment by jinfahua** [comment]
Can you telnet to port of Azure MQTT server?

**Comment by AzureUser123** [comment]
yes.. I think it's because the mqtt connection version. Now I'm trying to use v3.1.1. where should I change in the sourcecode to use a different mqtt version?

**Comment by AzureUser123** [comment]
I have changed PubSampler.java to use v3.1.1 by using mqtt.setVersion("3.1.1");
and it worked.

**Comment by jinfahua** [comment]
Cool, what's the default version? If it's a common requirement, we'd better expose the option in the UI.

**Comment by AzureUser123** [comment]
Default version is v3.1. But azure uses only v3.1.1 as the mqtt version to connect to the hub. It's better if the user has the option to select the version.. :)

**Comment by jinfahua** [comment]
OK, we'll add the feature to future release, thanks for your feedback.

**Comment by jinfahua** [comment]
Refer to below screenshot, added another option for MQTT protocol version. I don't have a MQTT server support 3.1.1, could help to try the fix attached in below? Thanks.

<img width="836" alt="2017-09-29 8 35 01" src="https://user-images.githubusercontent.com/8246540/30996161-36af26c4-a4f1-11e7-9d2a-2cb41a12f1a0.png">


[mqtt-xmeter-jar-with-dependencies.jar.zip](https://github.com/emqtt/mqtt-jmeter/files/1342737/mqtt-xmeter-jar-with-dependencies.jar.zip)

**Comment by AzureUser123** [comment]
Hi,
yes.. it was working. I have used port 8883 since azure iot hub does not allow port 1883. Thank you for integrating this.. :)

![untitledss](https://user-images.githubusercontent.com/30316860/31003746-dc910fd6-a50e-11e7-88b6-c7d42b496093.png)

**Comment by saurabh-saviant** [comment]
Hi,

I am trying to connect to Azure IoT Hub using JMeter but unable to connect. JMeter shows below error,

“Connection org.fusesource.mqtt.client.FutureConnection@2ae2a5 connected failed.” (Sampler request panel)
“ERROR - net.xmeter.samplers.ConnectionSampler: Could not connect: CONNECTION_REFUSED_NOT_AUTHORIZED org.fusesource.mqtt.client.MQTTException: Could not connect: CONNECTION_REFUSED_NOT_AUTHORIZED ” (Log viewer panel)

I have referred following links but no success,

https://github.com/emqtt/mqtt-jmeter/issues/21 (downloaded mqtt-xmeter-jar-with-dependencies.jar.zip)
https://github.com/emqtt/mqtt-jmeter/issues/23

Below is my MQTT Connection Sampler configuration,
Server name: {iothubhostname}
Port Number: 8883
Protocols: SSL (Duel SSL auth. ‘OFF’)
Username: {iothubhostname}/{device_id}/api-version=2016-11-14
Password: SAS Token generated

Kindly guide me through this. Thanks.

Regards,
Saurabh

**Comment by jinfahua** [comment]
You did not mention how you specify the clientID, is clientID correct? Thanks.

**Comment by saurabh-saviant** [comment]
Thanks for the reply. Sorry, I forgot to mention the clientID.

The clientID is exactly same as the 'Device ID' which is correct. This Device ID is registered in Azure IoT Hub so that I can send the messages to IoT Hub for this device.'Add random client id suffix' is 'Unchecked'
With this same configuration, I am able to send messages to IoT Hub using 'MQTTBox' tool (http://workswithweb.com/mqttbox.html) but unable to do the same with JMeter.
Please see attached the screenshot:
![jmeter_mqtt](https://user-images.githubusercontent.com/24788470/35557282-a9dfa0f8-05ca-11e8-8b86-458011345676.png)

**Comment by jinfahua** [comment]
You are not using the latest version of plugin, please download the latest version of JAR and replace your current. The latest version of plugin should have an option for selecting 'MQTT version', please select 3.1.1 in that drop-down box (which is also mentioned in homepage  - https://github.com/emqtt/mqtt-jmeter).

**Comment by saurabh-saviant** [comment]
@jinfahua 
The screenshot which I shared doesn't show the 'MQTT Version' field because I updated the JAVA version to 'Java version 8 update 161'. My previous version was 'Java 8 update 151' in which I could select the MQTT version to 3.1.1 which is supported by Azure IoT Hub. I think in 'Java version 8 update 161' there is an issue with the latest version of the plugin. Please check.
Now, back to my original problem
It worked with 'Java update 151'. I could connect to IoT Hub and send the message. Thanks a lot!
![image](https://user-images.githubusercontent.com/24788470/35565145-558616b4-05e2-11e8-9319-4546e683d2db.png)

**Comment by jinfahua** [comment]
Did you use Open JDK, Sun JDK or IBM JDK of version 8 update 161?

**Comment by saurabh-saviant** [comment]
'Sun JDK' which is now 'Java Oracle'
https://java.com/en/download/faq/release_changes.xml

**Comment by reubenrajan** [comment]
@saurabh-saviant - i am pretty new to Azure IOT, how do i get the password. I only see primary key and secondary keys in the Device registry in IOT hub. Do you i need to create separate SAS tokens? and if you could share a screenshot of the

**Comment by AzureUser123** [comment]
To create a SAS token you can download Azure device explorer. Download it from here or any other [source.](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer).
![image](https://user-images.githubusercontent.com/30316860/51961177-e3a2f700-2481-11e9-8865-51ede92fd6c0.png)
Add the IoT Hub Connection String, Hostname -> Click on Update. Then click on Generate SAS. This will create a SAS token. Use this token as the password.

**Comment by reubenrajan** [comment]
I found a way of using Azure IOT Tools on VSCode to generate the SAS password. but i am still seeing the same error: Response code: 501, Response message: Failed to establish Connection

**Comment by ranjanriseup** [comment]
> 
> 
> @jinfahua
> The screenshot which I shared doesn't show the 'MQTT Version' field because I updated the JAVA version to 'Java version 8 update 161'. My previous version was 'Java 8 update 151' in which I could select the MQTT version to 3.1.1 which is supported by Azure IoT Hub. I think in 'Java version 8 update 161' there is an issue with the latest version of the plugin. Please check.
> Now, back to my original problem
> It worked with 'Java update 151'. I could connect to IoT Hub and send the message. Thanks a lot!
> ![image](https://user-images.githubusercontent.com/24788470/35565145-558616b4-05e2-11e8-9319-4546e683d2db.png)

I have tried to get connection with MQTT server but still showing error as "Failed to establish Connection null."
![mqtt1](https://user-images.githubusercontent.com/56882605/67298399-d561a300-f508-11e9-8568-f1735cc8914b.png)
![mqtt2](https://user-images.githubusercontent.com/56882605/67298400-d561a300-f508-11e9-8f07-5faad9ba181b.png)
Please let me know what kind of missing content in this request.
As i have hit request from MQTTbox its getting connect.
![MQTT](https://user-images.githubusercontent.com/56882605/67298841-6fc1e680-f509-11e9-834d-4271980e76a0.png)
![mqttt](https://user-images.githubusercontent.com/56882605/67298842-705a7d00-f509-11e9-83b0-8225e531235d.png)
