### ISSUE TITLE
using "share conn in thread" - sample doesn't stop in connection get lost

### ISSUE THREAD

**Issue by Hmm90** [emqtt/mqtt-jmeter#32]
Using two mqtt Pub sampler in one thread (sampler  A and sampler B) with "share conn in thread" option. 
Sampler A build the connection and publish a message. 

Sampler B is publishing the message with a delay after sampler A. 

During that delay the connection get lost and sampler B is running in a exception:

2018-04-05 15:10:25,124 INFO n.x.s.PubSampler: Use the shared connection: org.fusesource.mqtt.client.CallbackConnection@46877199
2018-04-05 15:10:25,124 ERROR n.x.s.PubCallback: Peer disconnected
java.io.EOFException: Peer disconnected
	at org.fusesource.hawtdispatch.transport.AbstractProtocolCodec.read(AbstractProtocolCodec.java:331) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:710) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.SslTransport.drainInbound(SslTransport.java:276) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100) ~[mqtt-xmeter-jar-with-dependencies.jar:?]
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77) ~[mqtt-xmeter-jar-with-dependencies.jar:?]

But testplan didn't stop, also with a defined timeout of 5 seconds.

**Comment by rende2005** [comment]
@Hmm90 I tried to reproduce the issue based on your description, but didn't see the 2nd pub sampler failure. It worked as expected in my case (against an EMQ 2.0 server).

Would you share your test script, and what is the mqtt backend in your environment?

**Comment by rende2005** [comment]
![image](https://user-images.githubusercontent.com/10943265/38476604-3637cf3e-3be1-11e8-8282-e9d95f285e5c.png)
![image](https://user-images.githubusercontent.com/10943265/38476617-5352c51a-3be1-11e8-81db-0f172a15a0e8.png)

**Comment by rende2005** [comment]
![image](https://user-images.githubusercontent.com/10943265/38476677-a7a9118c-3be1-11e8-83b9-ee10b3d8d68d.png)
