### ISSUE TITLE
MQTT Connect Sampler show 500 error

### ISSUE THREAD

**Issue by andyzhouh** [emqtt/mqtt-jmeter#33]
/home/test/桌面/jietu.png
打印消息如下：
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2018/04/11 10:01:18 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2018/04/11 10:01:18 INFO  - net.xmeter.samplers.ConnectionSampler: *** Keeptime is: 1800 
2018/04/11 10:01:18 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : 线程组 
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group 线程组. 
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2018/04/11 10:01:18 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2018/04/11 10:01:18 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2018/04/11 10:01:18 INFO  - jmeter.threads.JMeterThread: Thread started: 线程组 1-1 
2018/04/11 10:01:18 ERROR - net.xmeter.samplers.ConnectionSampler: String index out of range: -10 java.lang.StringIndexOutOfBoundsException: String index out of range: -10
	at java.lang.String.substring(String.java:1911)
	at net.xmeter.Util.generateClientId(Util.java:34)
	at net.xmeter.samplers.ConnectionSampler.sample(ConnectionSampler.java:62)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
	at java.lang.Thread.run(Thread.java:748)

2018/04/11 10:01:18 ERROR - jmeter.samplers.SampleResult: setEndTime must be called after setStartTime java.lang.Throwable: Invalid call sequence
	at org.apache.jmeter.samplers.SampleResult.setEndTime(SampleResult.java:1046)
	at org.apache.jmeter.samplers.SampleResult.sampleEnd(SampleResult.java:1085)
	at net.xmeter.samplers.ConnectionSampler.sample(ConnectionSampler.java:93)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
	at java.lang.Thread.run(Thread.java:748)

2018/04/11 10:01:18 INFO  - net.xmeter.samplers.ConnectionSampler: Created the sampler results, will sleep current thread for 1800 sceconds 
2018/04/11 10:01:18 INFO  - net.xmeter.samplers.ConnectionSampler: Connection is null. 
2018/04/11 10:01:18 INFO  - jmeter.threads.JMeterThread: Thread is done: 线程组 1-1 
2018/04/11 10:01:18 INFO  - jmeter.threads.JMeterThread: Thread finished: 线程组 1-1 
2018/04/11 10:01:18 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2018/04/11 10:01:18 INFO  - net.xmeter.samplers.ConnectionSampler: in testEnded, isNonGUI=false, sleepFlag=false 
2018/04/11 10:01:18 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(false,*local*) 
![jietu](https://user-images.githubusercontent.com/12123660/38593196-c3acece0-3d72-11e8-99af-bb34aee45568.png)

**Comment by falalawang** [comment]
此错误由于ClinetId过长导致，此插件设定的最大的ClientId长度为23。

**Comment by falalawang** [comment]
Hi Andy,

第一个错误是由于Jmeter3.0版本低，内部方法不兼容造成的。我们建议您使用JMeter3.2或3.3版本。 后续我们会更新对JMeter版本限制的说明。
第二个错误是由于第一个错误抛出异常后，写sampler result失败导致从结果树中看不到结果。更换JMeter版本后问题就可以解决。

Thanks

**Comment by andyzhouh** [comment]
感谢，我试一下Jmeter更高的版本。

**Comment by andyzhouh** [comment]
用jmeter2.0的版本，可以正常发布消息。
