### ISSUE TITLE
CSV data set variables not supported by MQTT PUB sampler

### ISSUE THREAD

**Issue by Raul666** [emqtt/mqtt-jmeter#8]
I have "CSV dataset confg" in my test plan. Im sending values like URL, PORT via the csv files. 

- I added the beanshell sampler so that i could print out the value of the variables and the variable values are simply present.
- It works fine for Subscriber but the PUB SAmpler is not working.

**below is the log:**
2017/03/22 16:15:17 ERROR - net.xmeter.samplers.PubSampler: Illegal character in authority at index 6: ssl://${url}:${port} java.net.URISyntaxException: Illegal character in authority at index 6: ssl://${url}:${port}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.fusesource.mqtt.client.MQTT.setHost(MQTT.java:307)
	at net.xmeter.samplers.PubSampler.threadStarted(PubSampler.java:147)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:659)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:628)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:616)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:245)
	at java.lang.Thread.run(Unknown Source)

2017/03/22 16:15:17 ERROR - net.xmeter.samplers.PubSampler: Illegal character in authority at index 6: ssl://${url}:${port} java.net.URISyntaxException: Illegal character in authority at index 6: ssl://${url}:${port}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.fusesource.mqtt.client.MQTT.setHost(MQTT.java:307)
	at net.xmeter.samplers.PubSampler.threadStarted(PubSampler.java:147)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:659)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:628)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:616)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:245)
	at java.lang.Thread.run(Unknown Source)

2017/03/22 16:15:17 ERROR - net.xmeter.samplers.SubSampler: Illegal character in authority at index 6: ssl://${url}:${port} java.net.URISyntaxException: Illegal character in authority at index 6: ssl://${url}:${port}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.fusesource.mqtt.client.MQTT.setHost(MQTT.java:307)
	at net.xmeter.samplers.SubSampler.threadStarted(SubSampler.java:176)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:659)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:628)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:616)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:245)
	at java.lang.Thread.run(Unknown Source)

2017/03/22 16:15:17 ERROR - net.xmeter.samplers.PubSampler: Illegal character in authority at index 6: ssl://${url}:${port} java.net.URISyntaxException: Illegal character in authority at index 6: ssl://${url}:${port}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.fusesource.mqtt.client.MQTT.setHost(MQTT.java:307)
	at net.xmeter.samplers.PubSampler.threadStarted(PubSampler.java:147)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:659)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:628)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:616)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:245)
	at java.lang.Thread.run(Unknown Source)

2017/03/22 16:15:17 ERROR - net.xmeter.samplers.SubSampler: Illegal character in authority at index 6: ssl://${url}:${port} java.net.URISyntaxException: Illegal character in authority at index 6: ssl://${url}:${port}
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.fusesource.mqtt.client.MQTT.setHost(MQTT.java:307)
	at net.xmeter.samplers.SubSampler.threadStarted(SubSampler.java:176)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:659)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:996)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:978)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:628)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:616)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:245)
	at java.lang.Thread.run(Unknown Source)

2017/03/22 16:15:17 INFO  - jmeter.services.FileServer: Stored: C:\AAAdata\MQTTDS1.csv 
2017/03/22 16:15:17 ERROR - jmeter.util.BeanShellInterpreter: Error invoking bsh method: eval	In file: inline evaluation of: ``print "R url =" 112.118.10.118 print "RAUL port =" 8883 . . . ''

**Comment by rende2005** [comment]
Hi there!

I'm curious why pub sample is affected but sub is fine. Would you mind sending me the two jmx files without your actual target server info, so I will try to reproduce it?  

Meanwhile, we've found sometimes it's too early for JMeter to substitute the plugin parameters, (i.e. csv file is loaded at a later time).  If that's the case, would you please try __CSVRead function instead of external csv file?

**Comment by Raul666** [comment]
i will prefer sending via email. 
At which email can i send the jmx ?

**Comment by rende2005** [comment]
rendangen@xmeter.net please, as indicated in my profile.

**Comment by rende2005** [comment]
Hi Raul,  

it's confirmed JMeter loads csv files later than the execution of threadStarted() where we initialize mqtt connections with parameter substitution of hostname, port and so on. 

So two options here, 
1. you can try __CSVRead function replacing "CSV Data Set Config" element to define your hostname, port etc, this forces the csv file content loading.

2. I moved the connection init from threadStarted() to a later control point sample(), the "CSV Data Set Config" works good for me now.  I'm sending you a new plugin jar file via email, please give it a try and later I can commit the changes after receiving your feedback.

Thanks!

**Comment by rende2005** [comment]
please be noted, if connection init is moved to sample() function,  your first sub sampler loop will always return 0 message, since message probing is right after the subscription init logic, thus no message returns. However, after the loop interval, you can get the N messages from 2nd, 3rd loop, for the same virtual user, this works as expected.

**Comment by Raul666** [comment]
Hi Dang,


I have multiple tests where in same way data is inputted into test script using excelsheets from the localdrive.

I will first try your 2nd option. Will let you know by wednesday, as currently in foreign country for another project.
gr.,
Raul R.A.
________________________________

**Comment by Raul666** [comment]
I do not understand completely what you meant?

Actually i have a Publisher which when executed, i expect multiple responses in my subscriber. So based on the json rpc2 message im sending, i get the responses.


For example i have 3 parameters: 1 uuid, 2 brightness,3 color.

these properties are edited using jsonrpc2 message which send as payload in publisher,

then i expect to receive 3 messages for each property type in subscriber. So for my test it is important that i receive multiple responses.

Gr.,
Raul R.A

________________________________

**Comment by muyufan** [comment]
@rende2005  可以把更改了的代码提交吗？ 或者贴到这里？

我这边也需要CSV Data Set Config

**Comment by rende2005** [comment]
after subscriber is bound to a particular topic,  it enters "listen" mode,  and reports back all the messages received from the corresponding channel during the time interval. So generally, you may need to loop the sub sampler for sufficient times, with a fixed or random delay (e.g. 3000 ms). 
What I mean is,  the for first loop, sub may receive 0 message, but as long as you keep it running,  messages will arrive in the later loops.   You may start sub first, ensure it's in listen status, then launch the pub.   Yes, you can receive multiple responses, if the test scenario is properly designed.

**Comment by rende2005** [comment]
@muyufan  please check out the latest change and see if it helps.

**Comment by Raul666** [comment]
Tested **NOT OK**. with Option 2:  "CSV Data Set Config"
 Values could not be found by the sampler.

**Comment by rende2005** [comment]
My csv test passed with both pub and sub sampler,  sub can receive messages from pub.  

Raul, would you please show me your simplified testcase and corresponding error messages, together with jmeter.log, say with an email?

**Comment by Raul666** [comment]
FIXED. 
TEST OK.
Just tested with the new JAR and the issues is solved.  Please commit the changes in Release.
